#!/bin/bash

set -euo pipefail

# Installs list of packages
echo "Installing packages with pacman"

sudo pacman -Syu \
    bash-completion \
    grim \
    pavucontrol \
    kitty \
    hyprpaper \
    polkit \
    polkit-kde-agent \
    firewalld \
    thunar \
    gvfs \
    gnome-disk-utility \
    ristretto \
    gimp \
    w3m \
    imagemagick \
    ttf-jetbrains-mono \
    ttf-jetbrains-mono-nerd \
    waybar \
    btop \
    adobe-source-han-sans-jp-fonts \
    adobe-source-han-serif-jp-fonts \
    breeze \
    breeze-gtk \
    unzip \
    ttf-font-awesome \
    otf-font-awesome \
    slurp \
    flatpak \
    networkmanager \
    network-manager-applet \
    networkmanager-openvpn \
    networkmanager-qt5 \
    networkmanager-qt \
    nm-connection-editor \
    bubblewrap-suid \
    openresolv \
    wireguard-tools \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk \
    uwsm \
    ttf-firacode-nerd \
    qemu-desktop \
    libvirt \
    edk2-ovmf \
    virt-manager \
    dnsmasq \
    mpv

# Enable and config firewall
echo "Enabling and starting firewalld"
sudo systemctl enable --now firewalld.service

PRESET_FILE="/usr/lib/systemd/system-preset/90-systemd.preset"
if ! grep -q "^enable firewalld.service" "$PRESET_FILE"; then
    echo "Adding firewalld to system preset"
    echo "enable firewalld.service" | sudo tee -a "$PRESET_FILE"
fi

echo "Applying firewalld preset"
sudo systemctl preset firewalld.service

echo "Setting firewalld default zone and allowed ports/services"
sudo firewall-cmd --set-default-zone=drop

# Add allowed ports and services
PORTS=(80/tcp 443/tcp 53/udp 67/udp 68/udp)
for PORT in "${PORTS[@]}"; do
    echo "Adding port $PORT to drop zone"
    sudo firewall-cmd --zone=drop --add-port=$PORT --permanent
done

# Save and reload firewall config
sudo firewall-cmd --runtime-to-permanent
sudo firewall-cmd --reload

#Lock Root account
echo "Locking root account"
sudo passwd -l root

echo "Installing Flatpak apps"
FLATPAKS=(
  "io.gitlab.librewolf-community"
  "dev.vencord.Vesktop"
  "com.vscodium.codium"
)

for APP in "${FLATPAKS[@]}"; do
    echo "Installing $APP"
    flatpak install -y flathub "$APP"
done

echo "Post-install setup complete! Reboot recommended."